<?php
/**
 * View
 *
 * @category  CodeBlender
 * @package   Core
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
$this->title = 'Register';
?>

<h2>Register or <a href="/core/login" title="Login">Login</a></h2>

<?php
if ($this->messageType) {
    echo '<br />' . $this->layout_Message(array(
        'class' => $this->messageType,
        'title' => $this->messageTitle,
        'text' => $this->messageText
    ));
}

echo $this->form;
